version: "3"
services:
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:4.2.8-bionic
    expose:
      - 27017
    ports:
      - 27011:27017
    restart: always
    volumes:
      - /home/docker/keyfile:/home/keyfile
      - /home/docker/mongo1/data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/home/keyfile" , "--bind_ip_all", "--replSet", "rs1" ]
  mongo2:
    depends_on:
      - mongo1
    hostname: mongo2
    container_name: mongo2
    image: mongo:4.2.8-bionic
    expose:
      - 27017
    ports:
      - 27012:27017
    restart: always
    volumes:
      - /home/docker/keyfile:/home/keyfile
      - /home/docker/mongo2/data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/home/keyfile" , "--bind_ip_all", "--replSet", "rs1" ]
  mongo3:
    depends_on:
      - mongo1
      - mongo2
    hostname: mongo3
    container_name: mongo3
    image: mongo:4.2.8-bionic
    expose:
      - 27017
    ports:
      - 27013:27017
    restart: always
    volumes:
      - /home/docker/keyfile:/home/keyfile
      - /home/docker/mongo3/data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/home/keyfile" , "--bind_ip_all", "--replSet", "rs1" , "--eval", "initiate.js"]