version: "3"
services:
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: cka-mongodb:1.1
    expose:
      - 27017
    ports:
      - 27011:27017
    restart: always
    volumes:
      - /home/cka-mongodb/keyfile:/home/keyfile
      - /home/cka-mongodb/mongo1/data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/home/keyfile" , "--bind_ip_all", "--replSet", "rs1" ]
  mongo2:
    depends_on:
      - mongo1
    hostname: mongo2
    container_name: mongo2
    image: cka-mongodb:1.1
    expose:
      - 27017
    ports:
      - 27012:27017
    restart: always
    volumes:
      - /home/cka-mongodb/keyfile:/home/keyfile
      - /home/cka-mongodb/mongo2/data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/home/keyfile" , "--bind_ip_all", "--replSet", "rs1" ]
  mongo3:
    depends_on:
      - mongo1
      - mongo2
    hostname: mongo3
    container_name: mongo3
    image: cka-mongodb:1.1
    expose:
      - 27017
    ports:
      - 27013:27017
    restart: always
    volumes:
      - /home/cka-mongodb/keyfile:/home/keyfile
      - /home/cka-mongodb/mongo3/data:/data/db
      - /home/cka-mongodb/cka-Mongodb/initiate.js:/home/initiate.js
      - /home/cka-mongodb/cka-Mongodb/user.js:/home/user.js
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/home/keyfile" , "--bind_ip_all", "--replSet", "rs1" ]