version: "3"
services:
  cka-mongodb1:
    hostname: cka-mongodb1
    container_name: cka-mongodb1
    image: cka-mongodb:1.1
    expose:
      - 27017
    ports:
      - 27011:27017
    restart: always
    volumes:
      - /home/cka-mongodb/keyfile:/home/keyfile
      - /home/cka-mongodb/mongo1/data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/home/keyfile" , "--bind_ip_all", "--replSet", "rs1" ]
  cka-mongodb2:
    depends_on:
      - cka-mongodb1
    hostname: cka-mongodb2
    container_name: cka-mongodb2
    image: cka-mongodb:1.1
    expose:
      - 27017
    ports:
      - 27012:27017
    restart: always
    volumes:
      - /home/cka-mongodb/keyfile:/home/keyfile
      - /home/cka-mongodb/mongo2/data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/home/keyfile" , "--bind_ip_all", "--replSet", "rs1" ]
  cka-mongodb3:
    depends_on:
      - cka-mongodb1
      - cka-mongodb2
    hostname: cka-mongodb3
    container_name: cka-mongodb3
    image: cka-mongodb:1.1
    expose:
      - 27017
    ports:
      - 27013:27017
    restart: always
    volumes:
      - /home/cka-mongodb/keyfile:/home/keyfile
      - /home/cka-mongodb/mongo3/data:/data/db
      - /home/cka-mongodb/cka-Mongodb/initiate.js:/home/initiate.js
      - /home/cka-mongodb/cka-Mongodb/user.js:/home/user.js
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/home/keyfile" , "--bind_ip_all", "--replSet", "rs1" ]